<?php
return [
'name' => 'Ortifruver',
'website' => 'http://127.0.0.1:8081',
'company_phone' => '3203865580',
'email_from' => 'ortifruver@gmail.com',
'maintenance_mode' => '0',
'currency' => '$',
'shop_min_amount' => '10000.00',
'shipping_method' => '2',
'shipping_default_value' => '2000.00',
'shipping_amount_min' => '40000.00',
'to_go' => '1',
'social_facebook' => '#',
'social_instagram' => '#',
'social_twitter' => '#',
'social_youtube' => '#',
'social_whatsapp' => '#',
'payment_method_cash' => '1',
'payment_method_transfer' => '1',
'payment_method_transfer_accounts_bank' => 'Para depósitos o transferencias electrónicas, puede enviar el pago correspondiente a la siguiente cuenta: <br><strong> Ahorro a la mano: 03203865580<br>',
'payment_method_paypal' => '0',
'payment_method_credit_card' => '0',
'products_per_page' => '5',
'products_per_page_random' => '10',
'server_uploads_paths' => 'C:/Ortifruvervf/public/uploads',
'server_uploads_user_paths' => 'C:/Ortifruvervf/public/uploads_users',
'server_webapp_path' => 'C:/Ortifruvervf_pwa/',
]
?>
